# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'avopodo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for avopodo
  pod 'Firebase/Core'


  target 'avopodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'avopodo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for avopodo-tvOS

  target 'avopodo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
